module.exports = {
  UserService: require("./user-service"),
  ClientService: require("./client-service"),
  CourtroomService: require("./courtroom-service"),
  SpecificLawyerCourtroomService: require("./specificLawyerCourtroom-service"),
  PostService: require("./post-service"),
  GigService: require("./gig-service"),
  LeadService: require("./lead-service"),
  BlogService: require("./blog-service"),
  MailingListService: require("./mailingList-service"),
  GptServices: require("./gpt-service"),
  OrderService: require("./order-service"),
  BookingPayment: require("./bookingPayment-service"),
  PaymentService: require("./payment-service"),
  DbAutomationService: require("./dbAutomation-service"),
  ClientAdiraService: require("./clientAdira-service"),
  AdiraOrderService: require("./adiraOrder-service"),
};
