module.exports = {
  UserController: require("./user-controller"),
  ClientController: require("./client-controller"),
  CourtroomController: require("./coutroom-cotroller"),
  SpecificLawyerCourtroomController: require("./specificLawyerCourtroom-controller"),
  PostController: require("./post-controller"),
  LeadController: require("./lead-controller"),
  GigController: require("./gig-controller"),
  LegalGPTController: require("./legalgpt-controller"),
  BlogController: require("./blog-controller"),
  MailingListController: require("./mailingList-controller"),
  GptController: require("./gpt-controller"),
  CaseFinderController: require("./caseFinder-controller"),
  StripeController: require("./stripe-controller"),
  CashfreeController: require("./Cashfree-controller"),
  RazorpayController: require("./razorpay-controller"),
  AiDrafter: require("./aiDrafter-controller"),
  TimeBased: require("./timeBased-controller"),
  ClientAdiraController: require("./clientAdira-controller"),
};
